### ISSUE TITLE
Sunday October 29, 2017

### ISSUE THREAD

**Issue by ehashman** [dimsumjs/nyc#3]
Let's do it 😎

Me +2.
@mylesborins? @modernserf? Other friends???

**Comment by MylesBorins** [comment]
Yes please

Golden 🦄?

**Comment by sarahmeyer** [comment]
oh hi, hit me up guise

**Comment by MylesBorins** [comment]
Yay!

In 💯 committed to eating dumplings Sunday

**Comment by modernserf** [comment]
🙌

**Comment by ehashman** [comment]
Can I get a final count? I have 7 currently:

- me +2
- @modernserf +1
- @mylesborins
- @sarahmeyer

I'll show up at Golden Unicorn at 11:30am anticipating y'all for noon or so?

**Comment by MylesBorins** [comment]
I will aim to be there for 12... But perhaps we should push 30 due to post
Saturday Halloween hyginx?

On Oct 28, 2017 8:47 PM, "Elana Hashman" <notifications@github.com> wrote:

Can I get a final count? I have 7 currently:

   - me +2
   - @modernserf <https://github.com/modernserf> +1
   - @MylesBorins <https://github.com/mylesborins>
   - @sarahmeyer <https://github.com/sarahmeyer>

I'll show up at Golden Unicorn at 11:30am anticipating y'all for noon or so?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dimsumjs/nyc/issues/3#issuecomment-340229628>, or mute
the thread

**Comment by ehashman** [comment]
I'm assuming y'all will arrive noonish but they won't seat us until noon-thirty cuz large groups take forever

**Comment by ehashman** [comment]
Okay we are waiting, they say about 30 min for our group of 7.

**Comment by MylesBorins** [comment]
Waiting inside or outside? Should I bring umbrella?

**Comment by ehashman** [comment]
We're inside, you should bring an umbrella anyways, they will probably call us in the next 10 min or so?

**Comment by ehashman** [comment]
Okay, we are seated , second floor
